### ISSUE TITLE
Handling of Jupyter Notebooks in the repository

### ISSUE THREAD

**Issue by dgursoy** [tomography/tike#19]
This issue is to discuss if we need a version control on Notebooks in the repository. 

The Notebooks are meant to be interactive, which means we encourage users to play with them. So it is a question if we need versioning for these files? I'd rather have static Python scripts for tutorials that devs have control over and optimize in time, and have ipynb extensions listed in the .gitignore file.

**Comment by carterbox** [comment]
These notebooks are examples which can be rendered by a sphinx extension and added to the docs as html. I don't see them as any different from any other html page that would be included on readthedocs. These files need versioning because like any other doc page, you need to update them when you make changes to the API.

If you want interactive versions of these examples, we could host them on colaboratory/notebooks.azure(?), but we still need version control because the correct functioning of the notebook is tied to a specific API version.

**Comment by dgursoy** [comment]
`These notebooks are examples which can be rendered by a sphinx extension and added to the docs as html.` 

If this is the only purpose, then I'd go with Python scripts, because Sphinx can render them and add to the docs as html too. To me notebooks are good if you use them interactively in a web-browser, but are not that great for static docs. because they are more complicated to edit and run. 

Collabortory assumes the projects are pip installable, correct? Do they have any Conda option for building the projects?

**Comment by carterbox** [comment]
@dgursoy, can you give an example of Sphinx rendering Python scripts directly? Are you talking about the [Sphinx-Gallery extension](https://sphinx-gallery.github.io/stable/index.html)?
